{
  "formatVersion": "1.1",
  "component": {
    "group": "io.opentelemetry",
    "module": "opentelemetry-sdk-extension-autoconfigure",
    "version": "1.17.0-alpha",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-metrics",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-logs",
          "version": {
            "requires": "1.17.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-extension-autoconfigure-spi",
          "version": {
            "requires": "1.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-sdk-extension-autoconfigure-1.17.0-alpha.jar",
          "url": "opentelemetry-sdk-extension-autoconfigure-1.17.0-alpha.jar",
          "size": 51834,
          "sha512": "7d65824dc217474505e378f6b2e421c736871aff9aebea9a7bca8ee629ff987c7da995dff17f8215af6c49d861907f3c1bdbbe2ddcebae452f0acd99a665ba9f",
          "sha256": "632e505e6a2f9788afb4c77131353423958f222c50684e58176ed8ba361fc873",
          "sha1": "46b4ca4fd1eae8010fa0d77aba3a747a69a5967a",
          "md5": "34160de2cad5edd0467bcf4bc00ab2cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-semconv",
          "version": {
            "requires": "1.17.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-common",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-metrics",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-logs",
          "version": {
            "requires": "1.17.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-extension-autoconfigure-spi",
          "version": {
            "requires": "1.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-sdk-extension-autoconfigure-1.17.0-alpha.jar",
          "url": "opentelemetry-sdk-extension-autoconfigure-1.17.0-alpha.jar",
          "size": 51834,
          "sha512": "7d65824dc217474505e378f6b2e421c736871aff9aebea9a7bca8ee629ff987c7da995dff17f8215af6c49d861907f3c1bdbbe2ddcebae452f0acd99a665ba9f",
          "sha256": "632e505e6a2f9788afb4c77131353423958f222c50684e58176ed8ba361fc873",
          "sha1": "46b4ca4fd1eae8010fa0d77aba3a747a69a5967a",
          "md5": "34160de2cad5edd0467bcf4bc00ab2cf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-sdk-extension-autoconfigure-1.17.0-alpha-javadoc.jar",
          "url": "opentelemetry-sdk-extension-autoconfigure-1.17.0-alpha-javadoc.jar",
          "size": 124422,
          "sha512": "f0fdf21e57d5828b5bee8fe05ff0a357748c44f264056d3911ef51157921b3d03b00d30daba5b0ad0b34d536439797513cabb63f8912abcb65ac73fee0bbadd0",
          "sha256": "86b412ad38eed0131bb939578e4db60b91154d6b27cbc8a840ead20ef8b6bd84",
          "sha1": "0de371f0cb60f9a5c99f96e7aece5c6222c85eb3",
          "md5": "1f0467b3824cea911d77fd074c464f7b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-sdk-extension-autoconfigure-1.17.0-alpha-sources.jar",
          "url": "opentelemetry-sdk-extension-autoconfigure-1.17.0-alpha-sources.jar",
          "size": 24398,
          "sha512": "e170d2bde0f3c4f59e35a54a2a96776455c76e58b1acd6d1d4b4d7640ba12b97c15d793ff01d961c3a37c8f3c123d1e6e39f466bf886a8fbcbf24fb196505147",
          "sha256": "f2e46d8104734317d38da2eccd25d67089f0ba98ef51e23a423aa890cc195538",
          "sha1": "94078b749e935d5b71bd5409d24e729896ca4c50",
          "md5": "b9c4b698182b7fdb4d4bfde5729ad9a0"
        }
      ]
    }
  ]
}
