{
  "formatVersion": "1.1",
  "component": {
    "group": "io.opentelemetry",
    "module": "opentelemetry-sdk-extension-autoconfigure-spi",
    "version": "1.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-sdk-extension-autoconfigure-spi-1.17.0.jar",
          "url": "opentelemetry-sdk-extension-autoconfigure-spi-1.17.0.jar",
          "size": 10866,
          "sha512": "477887d3f653bc75fe9cdbf01e29b0f93bede1eb08f38242a171be0b54845ee6ccc60eb95b1c9de100a0ddb1452be8989b8dd068906c3b73b8f76f237fa3cd1d",
          "sha256": "929ffd64d542b60bc839f186dd6b63349fe4ed64778bbfee513e2fb38eaa7ac6",
          "sha1": "b97c6ba5818fd5c5436f08287ef90f62ac3e20b5",
          "md5": "245baa82ff506e48944732777ad8e39c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-metrics",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-logs",
          "version": {
            "requires": "1.17.0-alpha"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-sdk-extension-autoconfigure-spi-1.17.0.jar",
          "url": "opentelemetry-sdk-extension-autoconfigure-spi-1.17.0.jar",
          "size": 10866,
          "sha512": "477887d3f653bc75fe9cdbf01e29b0f93bede1eb08f38242a171be0b54845ee6ccc60eb95b1c9de100a0ddb1452be8989b8dd068906c3b73b8f76f237fa3cd1d",
          "sha256": "929ffd64d542b60bc839f186dd6b63349fe4ed64778bbfee513e2fb38eaa7ac6",
          "sha1": "b97c6ba5818fd5c5436f08287ef90f62ac3e20b5",
          "md5": "245baa82ff506e48944732777ad8e39c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-sdk-extension-autoconfigure-spi-1.17.0-javadoc.jar",
          "url": "opentelemetry-sdk-extension-autoconfigure-spi-1.17.0-javadoc.jar",
          "size": 166759,
          "sha512": "c00547040f377ef372efb8ffac7c81705aab0773f3eae38540bdec6561c0053f48a472453661c17d7b9c3d99125059a2b777fc78f85a2b5f2abbd4cf1599c685",
          "sha256": "97c115a7da6cc7f48104a188affc9fd83870a7ab157c4ef17fdd2cf2878a1c31",
          "sha1": "3afcac1633497a62d88c56fb2dc86f3b841a5da3",
          "md5": "7c1a8e119b559c88d22b03468874b909"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-sdk-extension-autoconfigure-spi-1.17.0-sources.jar",
          "url": "opentelemetry-sdk-extension-autoconfigure-spi-1.17.0-sources.jar",
          "size": 13473,
          "sha512": "255c79e40221402b1596a6e56016155db6896754fafda3d1f9543dc269cfe4224c16abba34c83816990143c31d00e735d749447236cd71bc9e37ecd8f590f610",
          "sha256": "e31ab6f8459ee82d9f0ce73c336e555f5d4dd08fc3416ddc803527cb209d25df",
          "sha1": "fcfe0223213554fcce72083435071d5f94a673f3",
          "md5": "58aa5994b90dee62258c146a3b4aa5a6"
        }
      ]
    }
  ]
}
