{
  "formatVersion": "1.1",
  "component": {
    "group": "io.opentelemetry",
    "module": "opentelemetry-context",
    "version": "1.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "opentelemetry-context-1.17.0.jar",
          "url": "opentelemetry-context-1.17.0.jar",
          "size": 45615,
          "sha512": "891925dd85051f6f57ccab75db416f3236479014fb9939718a109ce69e83571458ffa7d78c03bee15d6c6d29e75f08568be466d179f9830408995b40244b515f",
          "sha256": "ac5b7a7bda673b08d62d4dafe23a105ec4a7d0b7a967cda5597dcca994988227",
          "sha1": "fff5f3a2c36eaabbf2d4d9d578556967ba0b9eed",
          "md5": "cccb641b738b50a8b99175b0d72b794a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-context-1.17.0.jar",
          "url": "opentelemetry-context-1.17.0.jar",
          "size": 45615,
          "sha512": "891925dd85051f6f57ccab75db416f3236479014fb9939718a109ce69e83571458ffa7d78c03bee15d6c6d29e75f08568be466d179f9830408995b40244b515f",
          "sha256": "ac5b7a7bda673b08d62d4dafe23a105ec4a7d0b7a967cda5597dcca994988227",
          "sha1": "fff5f3a2c36eaabbf2d4d9d578556967ba0b9eed",
          "md5": "cccb641b738b50a8b99175b0d72b794a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-context-1.17.0-javadoc.jar",
          "url": "opentelemetry-context-1.17.0-javadoc.jar",
          "size": 156257,
          "sha512": "9c1bc484316931434584ca8498ceea62777da7830e776fec6fafeaf0e055c747b6f709fbfd239b63354afb20251f6cb88b392bf2fa64457d08d70510f89b06dc",
          "sha256": "bf0c4ea496077e3c2db60723648770ac3b17dfc8c7c5a35d4440d8bb5458e09d",
          "sha1": "0e33b95065169c4c1c21a977e2692c325d0639b0",
          "md5": "ff76e71a40dde102cc2ae4d9fbd76b59"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-context-1.17.0-sources.jar",
          "url": "opentelemetry-context-1.17.0-sources.jar",
          "size": 37063,
          "sha512": "b645d82cccaccbfe6e42c93de0387d8355183d905d6a4b26500e71ee949ece6facc51488135cdbe04a2ce17a2f5df0fe580c01209e390796d9f74823fc22fd17",
          "sha256": "7c04029713d713c2a5636689ca6c92c4fd14c0aba24247e6a4403124a9f45600",
          "sha1": "450d466a74d374ef2c6b009a9f290f08bc02ae8e",
          "md5": "b94406ebf55f81529cf6f91836b4967a"
        }
      ]
    }
  ]
}
