{
  "formatVersion": "1.1",
  "component": {
    "group": "io.opentelemetry",
    "module": "opentelemetry-sdk-metrics",
    "version": "1.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-common",
          "version": {
            "requires": "1.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-sdk-metrics-1.17.0.jar",
          "url": "opentelemetry-sdk-metrics-1.17.0.jar",
          "size": 282396,
          "sha512": "6c5a6dc3527acd9be753ef63e615f37a835536f5f5fe7413c602be488706995fd174aff2218fed05a2d6319fe5ccbb29e0eb69aa39b4775c8d282e11376d24c4",
          "sha256": "fd5be4b8923cb349ee2b8ef80f6cd31f46846be8c2579846bdc39b03cb3c3a6e",
          "sha1": "e7956b0b2c85dc408a87b4fece7b58273cd6933b",
          "md5": "6a20077b735992f8a759fe174e9ed080"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-common",
          "version": {
            "requires": "1.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-sdk-metrics-1.17.0.jar",
          "url": "opentelemetry-sdk-metrics-1.17.0.jar",
          "size": 282396,
          "sha512": "6c5a6dc3527acd9be753ef63e615f37a835536f5f5fe7413c602be488706995fd174aff2218fed05a2d6319fe5ccbb29e0eb69aa39b4775c8d282e11376d24c4",
          "sha256": "fd5be4b8923cb349ee2b8ef80f6cd31f46846be8c2579846bdc39b03cb3c3a6e",
          "sha1": "e7956b0b2c85dc408a87b4fece7b58273cd6933b",
          "md5": "6a20077b735992f8a759fe174e9ed080"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-sdk-metrics-1.17.0-javadoc.jar",
          "url": "opentelemetry-sdk-metrics-1.17.0-javadoc.jar",
          "size": 224659,
          "sha512": "7f24e34043fda32f4f24c363660132c080d44d2a04e878fbb5e1d53727ef02a42efa12bbc62ebe020f9544ad567cde78c670fbba42e8d79e5b68bdae78e463b8",
          "sha256": "c348f885b5153a30a7e7d4f7b414a6c471f3461eaec15653488e10928b49e636",
          "sha1": "11379d3e873d7c13b66d3ffb9baee3dac7a446a2",
          "md5": "8b54aae2e528f2049a597e2bce0c4693"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-sdk-metrics-1.17.0-sources.jar",
          "url": "opentelemetry-sdk-metrics-1.17.0-sources.jar",
          "size": 159571,
          "sha512": "5b0a6fbe049a719278f44cc4fdfee610a85477f0e18ec46b3eaad59127f24527a244e1440975c38ba4273ab667370dea3950ba71cd3f4b80dcca75ba0e8236d2",
          "sha256": "25f36393fc7e8f1f528af95e152e9af0c4a5a310300a4af610a588da2e6623d6",
          "sha1": "f900a06d485df74281783a7d821cabb6869c644a",
          "md5": "c7bbdb4fb860ef98ce1f982065ffd174"
        }
      ]
    }
  ]
}
