{
  "formatVersion": "1.1",
  "component": {
    "group": "io.opentelemetry",
    "module": "opentelemetry-exporter-common",
    "version": "1.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-exporter-common-1.17.0.jar",
          "url": "opentelemetry-exporter-common-1.17.0.jar",
          "size": 86450,
          "sha512": "7cf3952150f3257d7cbb330e64aee669979e45d6be10897436cc148f3100909b0c3e95f39f1a6e551ebf562822a9cf80dc58c8caf04c5e3c41a7a5171cf9ff67",
          "sha256": "d81ba85fe84c81e6b1a40c8351a619e1af40553cdecfe98254610137dcb025b0",
          "sha1": "fd746f2031b1f183b2c0e33156b75a73fe361e47",
          "md5": "c594d931351066749fb6ddc65d0a615a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "opentelemetry-exporter-common-1.17.0.jar",
          "url": "opentelemetry-exporter-common-1.17.0.jar",
          "size": 86450,
          "sha512": "7cf3952150f3257d7cbb330e64aee669979e45d6be10897436cc148f3100909b0c3e95f39f1a6e551ebf562822a9cf80dc58c8caf04c5e3c41a7a5171cf9ff67",
          "sha256": "d81ba85fe84c81e6b1a40c8351a619e1af40553cdecfe98254610137dcb025b0",
          "sha1": "fd746f2031b1f183b2c0e33156b75a73fe361e47",
          "md5": "c594d931351066749fb6ddc65d0a615a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-exporter-common-1.17.0-javadoc.jar",
          "url": "opentelemetry-exporter-common-1.17.0-javadoc.jar",
          "size": 371,
          "sha512": "e956d23e0e2c0fce8ad63bc5e9c4adeb522ef7e2e658f8acf24910c9a87755b8c5d33e3c749371f2ffade01ba9fd4d368362fd9c7a6b71b8439c3863b374e18b",
          "sha256": "fe7aae44cf86f419ecb590c380adf84ace943e8c40ea3d6fa455c6da77ea521b",
          "sha1": "ad33121535ac6ae52266187844a009458ca574f0",
          "md5": "ec018b1f82e1f4c32c9569bdbb07c04b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "opentelemetry-exporter-common-1.17.0-sources.jar",
          "url": "opentelemetry-exporter-common-1.17.0-sources.jar",
          "size": 52989,
          "sha512": "945771b14138e5e707eb5623d1a1bc36a43d84b752c8dca78c02bf70f5e0cf56d91af9e6185c3281c410cfe5dc1f69d8d1389ef25e2ebb951f474bc080da7c43",
          "sha256": "df93926df280e1e749a84608343dac4372c9c7ae00d2785322e790246e682bc8",
          "sha1": "a640785d0daf0dbd46947c38a2f479a06699cbfd",
          "md5": "69d7f9be1fefe3bffe35ba7807c487d3"
        }
      ]
    }
  ]
}
